retriever: reranker

retriever.ctx_src: wafer_ccnet
retriever.batch_size: 2
retriever.checkpoint_dir: ../../../../models/verifier/
retriever.retrieved_data_nr_ctxs: 100
retriever.retrieved_data_files:
    - dpr:../../../../outputs/predictions/evaluation.retrievers.dpr_remote.DPR/wafer-test.jsonl
    - gar:../../../../outputs/predictions/GAR/wafer-test.jsonl

evaluation_datasets:
  - wafer_test

# Uncomment to write the prediction files into the corresponding checkpoint directory
#output_folder: ${retriever.checkpoint_dir}/predictions/${retriever.checkpoint_load_suffix}__${retriever.ctx_src}




