retriever: dpr_remote

retriever.ctx_src: wafer_ccnet
retriever.batch_size: 1024
retriever.checkpoint_dir: ../../../../models/dense/biencoder/
retriever.rpc_retriever_cfg_file: ../../../../models/dense/index/discovery-config.txt

n_docs: 100
evaluation_datasets:
  - wafer_dev
  - wafer_test


# Uncomment to write the prediction files into the corresponding checkpoint directory
#output_folder: ${retriever.checkpoint_dir}/predictions/${retriever.checkpoint_load_suffix}__${retriever.ctx_src}




